#! /bin/bash

quiet="no"
if [ "$1" = "-q" ]; then
   quiet="yes"
   shift
fi

echo="echo"
if [ "$1" = "-n" ]; then
   echo="$echo -n"
   shift
fi

if [ -z "$1" ]; then
cat <<EOF
Usage: ${0##*/} [-q] [-n] command
   
-q = quiet
-n = no newline

Examples: ${0##*/} uptime
EOF
   exit 1
fi

for i in $(findhost pckr);do
   [[ "$quiet" = "yes" ]] || $echo "$i "
   $i "$*"
done
