#! /bin/bash

quiet="no"
if [ "$1" = "-q" ]; then
   quiet="yes"
   shift
fi

echo="echo"
if [ "$1" = "-n" ]; then
   echo="$echo -n"
   shift
fi

if [ -z "$1" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
cat <<EOF
Usage: ${0##*/} [-q] [-n] command
Run a command on all hosts

-q = quiet
-n = no newline

Examples: ${0##*/} uptime
EOF
   exit 1
fi

for i in $(findhost);do
   [[ "$quiet" = "yes" ]] || $echo "$i "
   ssh $i "$*"
done
