#! /bin/bash

#version 0.1f, 06.02.08 -- initial version
#version 0.1g, 16.04.08 -- better version show
#version 0.1h, 05.10.08 -- better sol for empty pattern
#version 0.1i, 05.10.08 -- added --hg option
#version 0.2,  23.09.09 -- subdir support and rcfile

usage="Usage: ${0##*/} <pattern>"
rcfile="$HOME/.findhost"

die () {
  echo "$*" >&2
  exit 1
}

help () {
  cat << eof
Find host matching to a pattern !
$usage
OPTIONS:
-s, --set DIR   Set the dir to look for the hosts
-h, --help      Show this help
-v, --version   Show version

Examples:   ${0##*/} pckr
            ${0##*/} thop
            ${0##*/}

Send bugs and comment to junghans@mpip-mainz.mpg.de
eof
}

while [ "${1#-}" != "$1" ]; do
  if [ "${1#--}" = "$1" ] && [ -n "${1:2}" ]; then
    if [ "${1#-[s]}" != "${1}" ]; then
       set -- "${1:0:2}" "${1:2}" "${@:2}"
    else
       set -- "${1:0:2}" "-${1:2}" "${@:2}"
    fi
 fi
 case $1 in 
   -h | --help)
    help
    exit 0;;
   -v | --version)
    echo "${0##*/}", $(sed -ne 's/^#\(version.*\) -- .*$/\1/p' $0 | sed -n '$p') by C. Junghans
    exit 0;;
   -s | --set)
    [ -d "$2" ] || die "Could not find dir '$2'"
    echo "$2" > $rcfile
    echo "Host dir to '$2'"
    exit 0;;
   --hg)
    echo "${0##*/}: $(sed -ne 's/^#version.* -- \(.*\)$/\1/p' $0 | sed -n '$p')"
    exit 0;;
  *)
   die "Unknown option '$1' - ignored"
   exit 1 ;;
 esac
done

[[ -f "$rcfile" ]] || die "Could not find rcfile '$rcfile', use --set first"
hostdir="$(cat $rcfile)"
[[ -d "$hostdir" ]] || die "Dir in rcfile is wrong, correct with --set option"

pattern="*$1*"
find $hostdir \! -type d -name "$pattern" -printf "%P\n"

