#! /bin/bash

if [ "$1" = "help" ] ||  [ "$1" = "--help" ]; then
   echo Generate a qsub script
   echo Usage: ${0##*/} 1\|2\|8 batch_name
   exit 1
fi

if [ $# -ne 2 ]; then
   ${0} --help
   exit 1
fi

batch_name="$2"
if [ -e $batch_name ]; then
   echo Batch file $batch_name already exists
   exit 1
fi

echo \#! /bin/bash >> $batch_name
if [ $1 -eq 1 ]; then
   echo \#$ -q all.q >> $batch_name
elif [ $1 -eq 2 ]; then
   echo \#$ -q dual.q >> $batch_name
   echo \#$ -pe lammpi2cores 2 >> $batch_name
elif [ $1 -eq 8 ]; then
   echo \#$ -q octal.q >> $batch_name
   echo \#$ -pe lammpi8cores 8 >> $batch_name
else
   echo Number of cpus unknown
   exit 1
fi
cat <<EOF >>$batch_name
#$ -cwd
#$ -j y
#$ -o screen.log
#$ -m e
#$ -M $USER\@mpip-mainz.mpg.de

cpus=$1
tcl_script=$(ls *.tcl)
restart_file="restart_flag.d"

if [ ! -r \$tcl_script ]; then
   echo tcl_script \$tcl_script not found
   exit 1;
fi

if [ ! -d \$PWD/Espresso ]; then
   echo Put a link to Espresso with \"ln -s something Espresso\"
   exit 1
fi

export ESPRESSO_SOURCE="\$PWD/Espresso"
export ESPRESSO_SCRIPTS="\$ESPRESSO_SOURCE/scripts"

export PATH="/opt/SGE/bin/lx26-amd64:/opt/lam/bin:\$PATH"

platform=\$(\$ESPRESSO_SOURCE/config/config.guess)
if [ -z "\$platform" ]; then
   echo config.guess not found in Espresso config dir
   exit 1
fi

#if obj dir is not there build it
if [ ! -e \$ESPRESSO_SOURCE/obj-\$platform ]; then
   cd \$ESPRESSO_SOURCE
   if [ \$cpus -eq 1 ]; then
      ./configure --with-mpi=fake
   else
      ./configure --with-mpi=lam
   fi
   make
   cd -
fi

rm -f restart_flag.d

if [ \$cpus -eq 1 ]; then
   \$ESPRESSO_SOURCE/obj-\$platform/Espresso_bin \$tcl_script
else
   mpirun -np \$cpus -x ESPRESSO_SCRIPTS \$ESPRESSO_SOURCE/obj-\$platform/Espresso_bin \$tcl_script
fi

if [ -r \$restart_file ]; then
   restart_flag=\$(cat \$restart_file)
else
   echo No restart_file \$restart_file found
   exit 1
fi

if [ "\$restart_flag" = "7" ]; then
   qsub $batch_name
fi
EOF

chmod 755 $batch_name
