#! /bin/bash

if [ -z "$1" ]; then
  echo Usage: ${0##*/} pattern
  exit
fi

if [ "$1" = "-h" ]; then
  echo Kills all jobs \(in qstat\) matching to a pattern!
  echo Usage: ${0##*/} pattern
  exit
fi

for i in $(qstat -u $USER | grep $USER | grep $1 | awk '{print $1}'); do
   qdel $i
done
#fs md5sum 48fbcd239353abc22951b585d2ba930c
