#! /bin/bash

qsub="/opt/SGE/bin/lx26-amd64/qsub"
runhost="thop02"

run="no"

if [ "$1" == "--run" ]; then
   run="yes"
   if [ -d "$2" ]; then
      cd $2
   else
     echo Directory \"$2\" not found
     exit 1
   fi
   shift 2
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
cat <<EOF   
Usage: ${0##*/} script scipt2 ...

This is a wrapper to run a local qsub script on $runhost
Internally it runs something (with checks) like:
   ssh $runhost "${0##*/} --run \$PWD scripts"
then ${0##*/} --run \$PWD (on $runhost) runs
   qsub script

It also make some dir changes and export to make 
this work nointeractive.

Be sure that the script is in the same dir on $runhost as on the your 
local host ($HOSTNAME). A use of /usr/scratch could be possible.

Send comments and bugs to: junghans@mpip-mainz.mpg.de
EOF
   exit 1
fi

if [ -z "$1" ]; then
   $0 --help
   exit 1
fi


for i in $*; do
   if [ ! -f $i ]; then
      echo script \"$i\" not found
      exit 1
   fi
done

if [ "$run" = "no" ]; then
   ssh $runhost "$0 --run $PWD $*"
   exit 0
fi

if [ "$runhost" != "$HOSTNAME" ]; then
   echo Error: this is the wrong host, want: $host, found: $HOSTNAME 
   exit 1
fi

#export for SGE
export SGE_ROOT=/opt/SGE

for i in $*; do
   $qsub $i
done
