#! /bin/bash

if [ -z "$1" ]; then
   echo Usage: ${0##*/} USER
   exit 1
fi

info=$(finger $1 2>&1)
if [ -z "${info/*no such user*}" ]; then
   echo No infomation about \"$1\" found
   exit 1
fi

echo -e "$info" | \
sed -n -e '1s/^.*Name:.\(.*\)$/\1/p' \
       -e '3s/^.*Office:.\(.*\)$/\1/p'